/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestingRouteImport } from './routes/resting'
import { Route as ThoughtThoughtIdRouteImport } from './routes/thought.$thoughtId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestingRoute = RestingRouteImport.update({
  id: '/resting',
  path: '/resting',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtThoughtIdRoute = ThoughtThoughtIdRouteImport.update({
  id: '/thought/$thoughtId',
  path: '/thought/$thoughtId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resting': typeof RestingRoute
  '/thought/$thoughtId': typeof ThoughtThoughtIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resting': typeof RestingRoute
  '/thought/$thoughtId': typeof ThoughtThoughtIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resting': typeof RestingRoute
  '/thought/$thoughtId': typeof ThoughtThoughtIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resting' | '/thought/$thoughtId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resting' | '/thought/$thoughtId'
  id: '__root__' | '/' | '/resting' | '/thought/$thoughtId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RestingRoute: typeof RestingRoute
  ThoughtThoughtIdRoute: typeof ThoughtThoughtIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resting': {
      id: '/resting'
      path: '/resting'
      fullPath: '/resting'
      preLoaderRoute: typeof RestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thought/$thoughtId': {
      id: '/thought/$thoughtId'
      path: '/thought/$thoughtId'
      fullPath: '/thought/$thoughtId'
      preLoaderRoute: typeof ThoughtThoughtIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestingRoute: RestingRoute,
  ThoughtThoughtIdRoute: ThoughtThoughtIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
